spring.application.name=ClothingAPP

spring.data.mongodb.uri=mongodb+srv://muthasiddhesh08_db_user:dspX7APf07MuYpnr@test1clothingapp.eke2r20.mongodb.net/?appName=Test1ClothingApp
spring.data.mongodb.database=clothingapp

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-swallow-size=25MB

#cloudinary:
CLOUDINARY_CLOUD_NAME=dk39sepjd
CLOUDINARY_API_KEY=747635654528163
CLOUDINARY_API_SECRET=4Wtp-VTyYJ80CWNGF63SfxD0PDM

#Gemini
GEMINI_API_KEY=AIzaSyC_yb9MkeS72XkYHtzZ0h4RdNKu3jqTZ3I


#JWT secretKey

jwtSecret=my_super_secure_secret_key_which_is_at_least_32_chars